package org.toshiba;

public class CameraDefine {
	public static final String ANTI_FLICKER = "http://192.168.42.1/setting/cgi-bin/fd_control_client?func=fd_set_video_anti_flicker";
    public static final String BEEP = "http://192.168.42.1/setting/cgi-bin/fd_control_client?func=fd_enable_beep";
    public static final String BIGIMG_IP = "http://192.168.42.1:8200/MediaItems/";
    public static final String CAMERA_OFF = "http://192.168.42.1/setting/cgi-bin/fd_control_client?func=fd_set_camera_off";
    public static final String CAR_DV = "http://192.168.42.1/setting/cgi-bin/fd_control_client?func=fd_enable_cardv";
    public static final String CAR_DV_SETTING = "http://192.168.42.1/setting/cgi-bin/fd_control_client?func=fd_get_cardv_setting";
    public static final String CONTRAST = "http://192.168.42.1/setting/cgi-bin/fd_control_client?func=fd_set_photo_contrast";
    public static final String DELIMG_IP = "http://192.168.42.1:8200/DeleteMedia/";
    public static final String ENABLE_DLNA = "http://192.168.42.1/setting/cgi-bin/fd_control_client?func=fd_enable_dlna&data=";
    public static final String ENTER_SHOOT = "http://192.168.42.1/setting/cgi-bin/fd_control_client?func=fd_send_app_status";
    public static final int FD_CAPTURE_MODE_PHOTO = 1;
    public static final int FD_CAPTURE_MODE_PHOTOBURST = 3;
    public static final int FD_CAPTURE_MODE_TIMELAPSE = 2;
    public static final int FD_CAPTURE_MODE_VIDEO = 0;
    public static final int FD_DISABLE_DLNA = 0;
    public static final int FD_ENABLE_DLNA = 1;
    public static final int FD_MEDIA_PHOTO = 1;
    public static final int FD_MEDIA_VIDEO = 0;
    public static final int FD_PHOTO_RES_12M = 0;
    public static final int FD_PHOTO_RES_3M = 2;
    public static final int FD_PHOTO_RES_5M = 1;
    public static final int FD_PHOTO_RES_COUNT = 3;
    public static final int FD_RECORD_START_RECORDING = 1;
    public static final int FD_RECORD_STOP_RECORDING = 0;
    public static final int FD_RECORD_TAKING_PHOTO = 2;
    public static final int FD_RTSP_STREAM_MODE_NUM = 3;
    public static final int FD_RTSP_STREAM_WQVGA_30 = 0;
    public static final int FD_RTSP_STREAM_WVGA_15 = 1;
    public static final int FD_RTSP_STREAM_WVGA_30 = 2;
    public static final int FD_STREAM_BITRATE_0_3 = 1;
    public static final int FD_STREAM_BITRATE_0_4 = 0;
    public static final int FD_STREAM_BITRATE_0_5 = 2;
    public static final int FD_STREAM_BITRATE_0_6 = 3;
    public static final int FD_STREAM_BITRATE_0_8 = 4;
    public static final int FD_STREAM_BITRATE_1 = 5;
    public static final int FD_STREAM_BITRATE_2 = 6;
    public static final int FD_STREAM_BITRATE_3 = 7;
    public static final int FD_STREAM_BITRATE_NUM = 8;
    public static final int FD_STREAM_FPS_10 = 2;
    public static final int FD_STREAM_FPS_15 = 1;
    public static final int FD_STREAM_FPS_3 = 5;
    public static final int FD_STREAM_FPS_30 = 0;
    public static final int FD_STREAM_FPS_5 = 4;
    public static final int FD_STREAM_FPS_6 = 3;
    public static final int FD_STREAM_FPS_NUM = 6;
    public static final int FD_STREAM_GOP_16 = 1;
    public static final int FD_STREAM_GOP_32 = 2;
    public static final int FD_STREAM_GOP_8 = 0;
    public static final int FD_STREAM_GOP_NUM = 3;
    public static final int FD_STREAM_RES_720P = 4;
    public static final int FD_STREAM_RES_NUM = 5;
    public static final int FD_STREAM_RES_QVGA = 1;
    public static final int FD_STREAM_RES_VGA = 2;
    public static final int FD_STREAM_RES_WQVGA = 0;
    public static final int FD_STREAM_RES_WVGA = 3;
    public static final int FD_VIDEO_RES_1080P = 0;
    public static final int FD_VIDEO_RES_1200P = 3;
    public static final int FD_VIDEO_RES_720P = 2;
    public static final int FD_VIDEO_RES_960P = 1;
    public static final int FD_VIDEO_RES_VGA = 5;
    public static final int FD_VIDEO_RES_WVGA = 4;
    public static final int FD_ZOOM_MAX_VALUE = 9;
    public static final String FILE_DEL = "http://192.168.42.1/setting/cgi-bin/fd_control_client?func=fd_del_media_file";
    public static final String FILE_PATH = "http://192.168.42.1/DCIM/";
//    public static final String FILE_PATH = "http://192.168.42.1/DCIM/";
//    http://192.168.42.1/DCIM/100MEDIA/ download all photos
    
    public static final String FILE_PATH_100MEDIA ="http://192.168.42.1/DCIM/100MEDIA/";
    		
    public static final String GET_BATTERY = "http://192.168.42.1/setting/cgi-bin/fd_control_client?func=fd_get_camera_battery";
    public static final String GET_CAMERA_CAPACITY = "http://192.168.42.1/setting/cgi-bin/fd_control_client?func=fd_get_camera_capacity";
    public static final String GET_CAMERA_INFO = "http://192.168.42.1/setting/cgi-bin/fd_control_client?func=fd_get_camera_info";
    public static final String GET_CAMERA_STATES = "http://192.168.42.1/setting/cgi-bin/fd_control_client?func=fd_get_record_status";
    public static final String GET_CAMERA_STATUS = "http://192.168.42.1/setting/cgi-bin/fd_control_client?func=fd_get_camera_status";
    public static final String GET_CAMERA_STATUS_2 = "http://192.168.42.1/setting/cgi-bin/fd_control_client?func=fd_get_camera_status_2";
    public static final String GET_LATEST_MEDIA = "http://192.168.42.1/setting/cgi-bin/fd_control_client?func=fd_get_latest_media_file&type=";
    public static final String GET_RECORD_STATUS = "http://192.168.42.1/setting/cgi-bin/fd_control_client?func=fd_get_record_status";
    public static final String GET_RECORD_STATUS2 = "http://192.168.42.1/setting/cgi-bin/fd_control_client?func=fd_get_record_status_2";
    public static final String LED_INDICATOR = "http://192.168.42.1/setting/cgi-bin/fd_control_client?func=fd_enable_led_indicator";
    public static final String MIC_SENSITIVITY = "http://192.168.42.1/setting/cgi-bin/fd_control_client?func=fd_set_mic_sensitivity";
    public static final String PHOTO_AE = "http://192.168.42.1/setting/cgi-bin/fd_control_client?func=fd_set_photo_ae";
    public static final String PHOTO_CONTINUE_SHOOT = "http://192.168.42.1/setting/cgi-bin/fd_control_client?func=fd_set_photo_continue_shooting";
    public static final String PHOTO_RES = "http://192.168.42.1/setting/cgi-bin/fd_control_client?func=fd_set_photo_resolution&data=";
    public static final String REBOOT_CAMERA = "http://192.168.42.1/setting/cgi-bin/fd_control_client?func=fd_reboot_camera";
    public static final String RECORD = "http://192.168.42.1/setting/cgi-bin/fd_control_client?func=fd_record";  // take a pic 
    public static final String RECORD_2 = "http://192.168.42.1/setting/cgi-bin/fd_control_client?func=fd_record_2&data=";
    									  // http://192.168.42.1/setting/cgi-bin/fd_control_client?func=fd_record_2&data=1   // start recording
    public static final String RESET_STREAM = "http://192.168.42.1/setting/cgi-bin/fd_control_client?func=fd_reset_stream";
    public static final String RESTORE_DEFAULT_SETTINGS = "http://192.168.42.1/setting/cgi-bin/fd_control_client?func=fd_restore_default_setting";
    public static final int RES_FAIL = 0;
    public static final int RES_SUCCESS = 1;
    public static final String ROTATING = "http://192.168.42.1/setting/cgi-bin/fd_control_client?func=fd_set_video_rotation";
    public static final String RTSP_STREAM = "rtsp://192.168.42.1/AmbaStreamTest";  // ??
    public static final String SELF_TIMER = "http://192.168.42.1/setting/cgi-bin/fd_control_client?func=fd_set_photo_self_timer";
    public static final String SERVER_IP = "http://192.168.42.1";
    public static final String SET_CAMERA_NAME = "http://192.168.42.1/setting/cgi-bin/fd_control_client?func=fd_set_camera_name";
    public static final String SET_DATE_TME = "http://192.168.42.1/setting/cgi-bin/fd_control_client?func=fd_set_time";
    public static final String SET_STREAM_BITRATE = "http://192.168.42.1/setting/cgi-bin/fd_control_client?func=fd_set_stream_bitrate&data=";
    public static final String SET_STREAM_ENCODE_CONFIG = "http://192.168.42.1/setting/cgi-bin/fd_control_client?func=fd_set_stream_encode_config&resolution=%d&framerate=%d&bitrate=%d&gop=%d";
    public static final String SET_STREAM_GOP = "http://192.168.42.1/setting/cgi-bin/fd_control_client?func=fd_set_stream_gop&data=";
    public static final String SET_STREAM_MODE = "http://192.168.42.1/setting/cgi-bin/fd_control_client?func=fd_set_stream_mode&data=";
    public static final String URL_BASIC = "http://192.168.42.1/setting/cgi-bin/fd_control_client?func=";
    public static final String URL_MODE_SET = "http://192.168.42.1/setting/cgi-bin/fd_control_client?func=fd_set_capture_mode&data=";
    public static final String VIDEO_FOV = "http://192.168.42.1/setting/cgi-bin/fd_control_client?func=fd_set_video_fov";
    public static final String VIDEO_FRAME = "http://192.168.42.1/setting/cgi-bin/fd_control_client?func=fd_set_video_framerate";
    public static final String VIDEO_RES = "http://192.168.42.1/setting/cgi-bin/fd_control_client?func=fd_set_video_resolution&data=";
    public static final String WHITE_BALANCE = "http://192.168.42.1/setting/cgi-bin/fd_control_client?func=fd_set_photo_wb";
    public static final String WIFI_CLIENT = "http://192.168.42.1/setting/cgi-bin/fd_control_client?func=fd_set_wifi_client";
    public static final String WIFI_MODE_AP = "http://192.168.42.1/setting/cgi-bin/fd_control_client?func=fd_set_wifi_mode_ap";
    public static final String WIFI_MODE_STATION = "http://192.168.42.1/setting/cgi-bin/fd_control_client?func=fd_set_wifi_mode_station";
    public static final String ZOOM = "http://192.168.42.1/setting/cgi-bin/fd_control_client?func=fd_dzoom&data=";
    
    public static final String VIDEO_SETTING_2 = "http://192.168.42.1/setting/cgi-bin/fd_control_client?func=fd_get_video_setting_2";
    
    public static final int CMD_CAPTURE_PHOTO = 2;
    public static final int CMD_ENABLE_DLNA = 12;
    public static final int CMD_GET_CAMERA_CAPACITY = 19;
    public static final int CMD_GET_CAMERA_INFO = 3;
    public static final int CMD_GET_CAMERA_STATUS = 4;
    public static final int CMD_GET_LATEST_MEDIA = 14;
    public static final int CMD_GET_RECORD_STATUS = 13;
    public static final int CMD_MODE_SET = 1;
    public static final int CMD_RESET_STREAM = 15;
    public static final int CMD_SET_DZOOM = 7;
    public static final int CMD_SET_PHOTO_RES = 6;
    public static final int CMD_SET_STREAM_BITRATE = 16;
    public static final int CMD_SET_STREAM_ENCODE_CONFIG = 20;
    public static final int CMD_SET_STREAM_GOP = 18;
    public static final int CMD_SET_STREAM_MODE = 17;
    public static final int CMD_SET_VIDEO_RES = 5;
    public static final int CMD_START_CON_SHOOT = 10;
    public static final int CMD_START_RECORD_VIDEO = 8;
    public static final int CMD_STOP_CON_SHOOT = 11;
    public static final int CMD_STOP_RECORD_VIDEO = 9;
    

}